apiVersion: "secretmanager.cnrm.cloud.google.com/v1beta1"
kind: "SecretManagerSecret"
metadata:
  name: "rspotify-tripproberts-hash"
  namespace: "tripp-personal"
spec:
  replication:
    automatic: true
  resourceID: "rspotify-tripproberts-hash"
